version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PublishingAliasName=\"current\" StageName=\"prod\" FunctionName=\"CodeGuruLambda\""
image_repositories = []
