name: Analyze with CodeGuru Reviewer

on: [push, pull_request]

permissions:
    id-token: write
    contents: read
    security-events: write 

jobs:
  build:
    name: Clone your repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build gradle package
      run: mvn compile -DskipTests

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::727015569506:role/GitHubActionRole
        aws-region: us-east-1

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      continue-on-error: false
      with:          
        s3_bucket: codeguru-reviewer-build-artifacts-727015569506-us-east-1
        build_path: ./target/classes

    - name: Upload review result
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
