name: CodeGuru Workflow
on:
  push:
    branches:
      - dev # or the name of your main branch , this can change again.Mar 12 3:40 PM EST

jobs:
  deploy:
    runs-on: ubuntu-latest #for SRG
    steps:

# Step 1: Checkout the repository and provide your AWS credentials
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # Region to access CodeGuru 

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Codeguru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      with:
        build_path: target  # Path to the build artifact
        s3_bucket: codeguru-reviewer-my-bucket-mar11  # S3 Bucket with "codeguru-reviewer-*" prefix
    
    # Step 3: Upload results into GitHub
    - name: Upload review result
      if: ${{ github.event_name != 'push' }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json